import express from 'express';
import authRoutes from '../routes/authRoutes.js';
import cropRoutes from '../routes/cropRoutes.js';
import orderRoutes from '../routes/orderRoutes.js';
import adminRoutes from '../routes/adminRoutes.js';
import healthRoutes from '../routes/healthRoutes.js';
import aiRoutes from '../routes/aiRoutes.js';
import farmerRoutes from '../routes/farmerRoutes.js';
import reviewRoutes from '../routes/reviewRoutes.js';
import negotiationRoutes from '../routes/negotiationRoutes.js';
import dataAccessRoutes from '../routes/dataAccessRoutes.js';
import messageRoutes from '../routes/messageRoutes.js';
import cookieParser from 'cookie-parser';
import csrfProtection from '../middleware/csrf.js';
import errorHandler from '../middleware/errorHandler.js';

const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(csrfProtection);
app.use('/health', healthRoutes);
app.use('/healthz', healthRoutes);
app.use('/auth', authRoutes);
app.use('/api/auth', authRoutes);
app.use('/api/crops', cropRoutes);
app.use('/api/orders', orderRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/ai', aiRoutes);
app.use('/api/farmer', farmerRoutes);
app.use('/api/reviews', reviewRoutes);
app.use('/api/negotiations', negotiationRoutes);
app.use('/api/data', dataAccessRoutes);
app.use('/api/messages', messageRoutes);
app.use(errorHandler);

export default app;
